import { idArg, nonNull, queryField } from "nexus";
import { getWorkspaceInvitation } from "../../../database/workspace/getWorkspaceInvitation";
import { formatWorkspaceInvitation } from "../../../types/workspace";
import { WorkspaceInvitation } from "../../types/workspace";

export const workspaceInvitationQuery = queryField((t) => {
  t.field("workspaceInvitation", {
    type: WorkspaceInvitation,
    args: {
      id: nonNull(idArg()),
    },
    async resolve(root, args, context) {
      const workspaceInvitationId = args.id;
      // Explanation why this query is not protected by authentication:
      // The data can only be fetched if the correct `workspaceInvitationId` is passed along.
      // Since this ID is a UUID generated by the DB when creating an invitation and can't
      // be guessed this basically acts as authentication for this specific query.
      const workspaceInvitation = await getWorkspaceInvitation({
        workspaceInvitationId,
      });
      return formatWorkspaceInvitation(workspaceInvitation);
    },
  });
});
